// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkrquzrvhuxggxtfxvoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcnF1enJ2aHV4Z2d4dGZ4dm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTg3NTcsImV4cCI6MjA3MzUzNDc1N30.OutPyf_u3NJ78VTXZiIRlrGgWPEh4JhsIGG5sjmZ8Zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});